features:
  node_user_picture: 1
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 0
logo:
  use_default: 0
  path: 'public://Screen Shot 2016-01-25 at 1.25.31 PM_0.png'
favicon:
  use_default: 1
  path: ''
main_layout: fixed
login_popup: 1
sticky_footer: 1
semantic_ui: 1
sidr: 1
